version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-v1-{{ checksum "./ecsite2/composer.lock" }}
      - run: composer install -n --prefer-dist --working-dir=./ecsite2/
      - save_cache:
          key: composer-v1-{{ checksum "./ecsite2/composer.lock" }}
          paths:
            - ./laravel-ci2/vendor
      - run: cd ecsite2/; npm ci
      - run: cd ecsite2/; npm run dev
      - run:
          name: php test
          command: php ./ecsite2/vendor/bin/phpunit --configuration=./ecsite2/phpunit.xml
