version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: circleci/postgres:11.6-alpine
        environment:
          POSTGRES_DB: laraec
          POSTGRES_USER: default
          POSTGRES_PASSWORD: secret
    environment:
      APP_ENV: testing
      DB_CONNECTION: pgsql
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DATABASE: laraec
      DB_USERNAME: default
      DB_PASSWORD: secret
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-v1-{{ checksum "./ecsite2/composer.lock" }}
      - run: composer install -n --prefer-dist --working-dir=./ecsite2/
      - save_cache:
          key: composer-v1-{{ checksum "./ecsite2/composer.lock" }}
          paths:
            - ./ecsite2/vendor
      - restore_cache:
          key: npm-v1-{{ checksum "./ecsite2/package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d ./ecsite2/node_modules ]; then
              cd ecsite2/; npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "./ecsite2/package-lock.json" }}
          paths:
            - ./ecsite2/node_modules
      - run: cd ecsite2/; npm run dev
      - run:
          name: get ready for postgres
          command: |
            sudo apt-get update
            sudo apt-get install libpq-dev
            sudo docker-php-ext-install pdo_pgsql
            dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: cd ecsite2/; php artisan config:clear
      - run:
          name: php test
          command: php ./ecsite2/vendor/bin/phpunit --configuration=./ecsite2/phpunit.xml
