version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1
      - run: composer install -n --prefer-dist --working-dir=./ecsite2/
      - run: cd ecsite2/; npm ci
      - run: cd ecsite2/; npm run dev
      - run:
          name: php test
          command: php ./ecsite2/vendor/bin/phpunit --configuration=./ecsite2/phpunit.xml
